# 后端配置 - 必填
backend:
  name: git-gateway # 使用 GitHub 作为后端
  branch: main

# 媒体文件配置
media_folder: "source/images/uploads" # 用户上传的图片将保存在此
public_folder: "/images/uploads" # 在编辑器中，图片的公开访问路径

# 本地后端（可选，用于开发测试）
# local_backend: true # 启用本地后端

# 集合配置 - 定义内容模型
collections:
  # 定义博客文章集合
  - name: "posts" # 集合名称
    label: "文章" # 后台显示名称
    folder: "source/_posts" # 博客文章存放的文件夹
    create: true # 允许用户创建新文章
    slug: "{{slug}}" # 新文章的文件名格式
    fields: # 定义文章的字段
      - { label: "标题", name: "title", widget: "string" }
      - {
          label: "日期",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
        }
      - { label: "标签", name: "tags", widget: "list", default: [] }
      - { label: "分类", name: "categories", widget: "list", default: [] }
      - { label: "正文", name: "body", widget: "markdown" }
